// Defines the GameItem interface and exports the comprehensive arcadeGames array.

export interface GameItem {
  id: number | string;
  title: string;
  src: string;
  width: number;
  height: number;
  thumbnail: string;
  tags: string[];
  rating?: number;
  author: string;
  featured?: boolean;
  aiHint?: string;
}

export const genericThumbnail = "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMTUwIj48cmVjdCB3aWR0aD0iMjUwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iIzMzMyIvPjxwYXRoIGQ9Ik03MCw2MGMwLDAsMTAsNDAsMCw0MCBzMjAsMCwyMCwwIHMxMCwtNDAsMCwtNDAiIHN0cm9rZT0iI2ZmZiIgc3Ryb2tlLXdpZHRoPSIyIiBmaWxsPSJub25lIi8+PHBhdGggZD0iTTEzMCw2MGMwLDAsMTAsNDAsMCw0MCBzMjAsMCwyMCwwIHMxMCwtNDAsMCwtNDAiIHN0cm9rZT0iI2ZmZiIgc3Ryb2tlLXdpZHRoPSIyIiBmaWxsPSJub25lIi8+PHRleHQgeD0iMTI1IiB5PSIxMjUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iIzg4OCI+R2FtZTwvdGV4dD48L3N2Zz4=";

function generateAiHint(title: string): string {
  const words = title.toLowerCase().split(' ').filter(word => word.length > 1 && !['a', 'the', 'of', 'and', 'for', 'in', 'on', 'to', 'with', '&', 'at', '2', '3', '4', '5', '6'].includes(word));
  if (words.length === 1 && words[0]) {
      return `${words[0]} game`;
  }
  if (words.length === 0) {
    return 'interactive game';
  }
  return words.slice(0, 2).join(' ');
}

function generateTags(title: string, defaultTags: string[] = ['html5']): string[] {
    const titleWords = title.toLowerCase().split(' ').filter(tag => tag.length > 2 && !['the', 'of', 'and', 'a', 'game', 'player', 'radio', 'simulator', 'classic', 'client', '2', '3d'].includes(tag) );
    const uniqueTags = [...new Set([...titleWords.slice(0,2), ...defaultTags])];
    return uniqueTags.slice(0, 4); // Limit to 4 tags
}

export const arcadeGames: GameItem[] = [
    {
        id: "wakeupwork",
        title: "Wake Up Work",
        src: "https://wakeupwork.on.websim.ai/?v=3",
        width: 800,
        height: 600,
        thumbnail: "https://placehold.co/600x400.png",
        aiHint: generateAiHint("Wake Up Work"),
        tags: generateTags("Wake Up Work", ["interactive", "experience", "simulation"]),
        author: "WebSim.ai",
        featured: true,
    },
    {
        id: "fever-dream",
        title: "Fever Dream",
        src: "https://fever-dream.on.websim.ai/",
        width: 800,
        height: 600,
        thumbnail: "https://placehold.co/600x400.png",
        aiHint: generateAiHint("Fever Dream"),
        tags: generateTags("Fever Dream", ["visualizer", "abstract", "trippy", "music"]),
        author: "WebSim.ai",
        featured: true,
    },
    {
        id: "multiplayer-cattle-racing-game-5",
        title: "Multiplayer Cattle Racing",
        src: "https://websim.ai/@SOFAKINGSADBOI/multiplayer-cattle-racing-game-5/",
        width: 960,
        height: 540,
        thumbnail: "https://placehold.co/600x400.png",
        aiHint: generateAiHint("Multiplayer Cattle Racing"),
        tags: generateTags("Multiplayer Cattle Racing", ["multiplayer", "racing", "fun", "animal"]),
        author: "SOFAKINGSADBOI",
    },
    {
        id: "saucelab-dj",
        title: "Saucelab DJ",
        src: "https://saucelab-dj.on.websim.ai/",
        width: 800,
        height: 600,
        thumbnail: "https://placehold.co/600x400.png",
        aiHint: generateAiHint("Saucelab DJ"),
        tags: generateTags("Saucelab DJ", ["music", "dj", "interactive", "audio"]),
        author: "WebSim.ai",
    },
    {
        id: "trippybeats",
        title: "Trippy Beats",
        src: "https://trippybeats.on.websim.ai/",
        width: 800,
        height: 600,
        thumbnail: "https://placehold.co/600x400.png",
        aiHint: generateAiHint("Trippy Beats"),
        tags: generateTags("Trippy Beats", ["music", "visualizer", "trippy", "audio"]),
        author: "WebSim.ai",
    },
    {
        id: "lofi",
        title: "Lofi Player",
        src: "https://lofi.on.websim.ai/",
        width: 800,
        height: 600,
        thumbnail: "https://placehold.co/600x400.png",
        aiHint: generateAiHint("Lofi Player"),
        tags: generateTags("Lofi Player", ["music", "lofi", "chill", "beats", "audio"]),
        author: "WebSim.ai",
        featured: true,
    },
    {
        id: "dubstepbanger",
        title: "Dubstep Banger",
        src: "https://dubstepbanger.on.websim.ai/",
        width: 800,
        height: 600,
        thumbnail: "https://placehold.co/600x400.png",
        aiHint: generateAiHint("Dubstep Banger"),
        tags: generateTags("Dubstep Banger", ["music", "dubstep", "electronic", "audio"]),
        author: "WebSim.ai",
    },
    {
        id: "vaporwave",
        title: "Vaporwave Player",
        src: "https://vaporwave.on.websim.ai/",
        width: 800,
        height: 600,
        thumbnail: "https://placehold.co/600x400.png",
        aiHint: generateAiHint("Vaporwave Player"),
        tags: generateTags("Vaporwave Player", ["music", "vaporwave", "aesthetic", "retro", "audio"]),
        author: "WebSim.ai",
    },
    {
        id: "countryradio",
        title: "Country Radio",
        src: "https://countryradio.on.websim.ai/",
        width: 800,
        height: 600,
        thumbnail: "https://placehold.co/600x400.png",
        aiHint: generateAiHint("Country Radio"),
        tags: generateTags("Country Radio", ["music", "country", "radio", "audio"]),
        author: "WebSim.ai",
    },
    {
        id: "tipper",
        title: "Tipper Visualizer",
        src: "https://tipper.on.websim.ai/",
        width: 800,
        height: 600,
        thumbnail: "https://placehold.co/600x400.png",
        aiHint: generateAiHint("Tipper Visualizer"),
        tags: generateTags("Tipper Visualizer", ["music", "visualizer", "tipper", "electronic", "audio"]),
        author: "WebSim.ai",
    },
    {
        id: "sprunki-adventure",
        title: "Sprunki Adventure",
        src: "https://sprunki-adventure.on.websim.ai/",
        width: 800,
        height: 600,
        thumbnail: "https://placehold.co/600x400.png",
        aiHint: generateAiHint("Sprunki Adventure"),
        tags: generateTags("Sprunki Adventure", ["adventure", "platformer", "indie"]),
        author: "WebSim.ai",
    },
    { id: 'deal', title: 'Deal or No Deal', src: 'https://gamesyte.github.io/deal/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/deal/cover.svg', author: 'GameSyte', tags: generateTags('Deal or No Deal'), aiHint: generateAiHint('Deal or No Deal') },
    { id: 'skills', title: 'Soccer Skills', src: 'https://gamesyte.github.io/skills/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/skills/cover.svg', author: 'GameSyte', tags: generateTags('Soccer Skills'), aiHint: generateAiHint('Soccer Skills') },
    { id: 'slope3', title: 'Slope 3', src: 'https://gamesyte.github.io/slope3/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/slope3/cover.svg', author: 'GameSyte', tags: generateTags('Slope 3'), aiHint: generateAiHint('Slope 3') },
    { id: 'snow', title: 'Snowball Fighter', src: 'https://gamesyte.github.io/snow/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/snow/cover.svg', author: 'GameSyte', tags: generateTags('Snowball Fighter'), aiHint: generateAiHint('Snowball Fighter') },
    { id: 'space', title: 'Spacebar Clicker', src: 'https://gamesyte.github.io/space/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/space/cover.svg', author: 'GameSyte', tags: generateTags('Spacebar Clicker'), aiHint: generateAiHint('Spacebar Clicker') },
    { id: 'pi', title: 'π Client', src: 'https://gamesyte.github.io/pi/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/pi/cover.svg', author: 'GameSyte', tags: generateTags('π Client'), aiHint: generateAiHint('π Client') },
    { id: 'pre', title: 'Precision Client', src: 'https://gamesyte.github.io/pre/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/pre/cover.svg', author: 'GameSyte', tags: generateTags('Precision Client'), aiHint: generateAiHint('Precision Client') },
    { id: 'shadow', title: 'Shadow Client', src: 'https://gamesyte.github.io/shadow/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/shadow/cover.svg', author: 'GameSyte', tags: generateTags('Shadow Client'), aiHint: generateAiHint('Shadow Client') },
    { id: 'xp', title: 'Windows XP', src: 'https://gamesyte.github.io/xp/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/xp/cover.svg', author: 'GameSyte', tags: generateTags('Windows XP'), aiHint: generateAiHint('Windows XP') },
    { id: 'drag', title: 'Dragon Client', src: 'https://gamesyte.github.io/drag/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/drag/cover.svg', author: 'GameSyte', tags: generateTags('Dragon Client'), aiHint: generateAiHint('Dragon Client') },
    { id: 'ayun', title: 'Ayuncraft 1.5.2', src: 'https://gamesyte.github.io/ayun/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/ayun/cover.svg', author: 'GameSyte', tags: generateTags('Ayuncraft 1.5.2'), aiHint: generateAiHint('Ayuncraft 1.5.2') },
    { id: 'inf', title: 'Minecraft Infdev', src: 'https://gamesyte.github.io/inf/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/inf/cover.svg', author: 'GameSyte', tags: generateTags('Minecraft Infdev'), aiHint: generateAiHint('Minecraft Infdev') },
    { id: 'minesweeper', title: 'Minesweeper', src: 'https://gamesyte.github.io/minesweeper/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/minesweeper/cover.svg', author: 'GameSyte', tags: generateTags('Minesweeper'), aiHint: generateAiHint('Minesweeper') },
    { id: 'poom', title: 'POOM', src: 'https://gamesyte.github.io/poom/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/poom/cover.svg', author: 'GameSyte', tags: generateTags('POOM'), aiHint: generateAiHint('POOM') },
    { id: 'solitaire', title: 'Solitaire', src: 'https://gamesyte.github.io/solitaire/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/solitaire/cover.svg', author: 'GameSyte', tags: generateTags('Solitaire'), aiHint: generateAiHint('Solitaire') },
    { id: 'spankthemonkey', title: 'Spank the Monkey', src: 'https://gamesyte.github.io/spankthemonkey/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/spankthemonkey/cover.svg', author: 'GameSyte', tags: generateTags('Spank the Monkey'), aiHint: generateAiHint('Spank the Monkey') },
    { id: 'cmm-client', title: 'CMM Client', src: 'https://gamesyte.github.io/cmm-client/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/cmm-client/cover.svg', author: 'GameSyte', tags: generateTags('CMM Client'), aiHint: generateAiHint('CMM Client') },
    { id: 'pool', title: 'Pool', src: 'https://gamesyte.github.io/pool/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/pool/cover.svg', author: 'GameSyte', tags: generateTags('Pool'), aiHint: generateAiHint('Pool') },
    { id: 'yohoho', title: 'Yohoho.io', src: 'https://gamesyte.github.io/yohoho/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/yohoho/cover.svg', author: 'GameSyte', tags: generateTags('Yohoho.io'), aiHint: generateAiHint('Yohoho.io') },
    { id: 'tube-jumpers', title: 'Tube Jumpers', src: 'https://gamesyte.github.io/tube-jumpers/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/tube-jumpers/cover.svg', author: 'GameSyte', tags: generateTags('Tube Jumpers'), aiHint: generateAiHint('Tube Jumpers') },
    { id: 'hillclimbracing2', title: 'Hill Climb Racing 2', src: 'https://gamesyte.github.io/hillclimbracing2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/hillclimbracing2/cover.svg', author: 'GameSyte', tags: generateTags('Hill Climb Racing 2'), aiHint: generateAiHint('Hill Climb Racing 2') },
    { id: 'doom', title: 'DOOM', src: 'https://gamesyte.github.io/doom/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/doom/cover.svg', author: 'GameSyte', tags: generateTags('DOOM'), aiHint: generateAiHint('DOOM') },
    { id: 'awesometanks', title: 'Awesome Tanks', src: 'https://gamesyte.github.io/awesometanks/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/awesometanks/cover.svg', author: 'GameSyte', tags: generateTags('Awesome Tanks'), aiHint: generateAiHint('Awesome Tanks') },
    { id: 'bubbleshooter', title: 'Bubble Shooter', src: 'https://gamesyte.github.io/bubbleshooter/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/bubbleshooter/cover.svg', author: 'GameSyte', tags: generateTags('Bubble Shooter'), aiHint: generateAiHint('Bubble Shooter') },
    { id: 'pong', title: 'Pong', src: 'https://gamesyte.github.io/pong/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/pong/cover.svg', author: 'GameSyte', tags: generateTags('Pong'), aiHint: generateAiHint('Pong') },
    { id: 'flappyplane', title: 'Flappy Plane', src: 'https://gamesyte.github.io/flappyplane/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/flappyplane/favicon.ico', author: 'GameSyte', tags: generateTags('Flappy Plane'), aiHint: generateAiHint('Flappy Plane') },
    { id: 'adofai', title: 'A Dance of Fire & Ice', src: 'https://gamesyte.github.io/adofai/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/adofai/icon.png', author: 'GameSyte', tags: generateTags('A Dance of Fire & Ice'), aiHint: generateAiHint('A Dance of Fire & Ice') },
    { id: 'online-mc', title: 'Resent Client', src: 'https://gamesyte.github.io/online-mc/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/online-mc/logo.png', author: 'GameSyte', tags: generateTags('Resent Client'), aiHint: generateAiHint('Resent Client') },
    { id: 'offline-mc', title: 'Eaglercraft 1.5.2', src: 'https://gamesyte.github.io/offline-mc/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/offline-mc/logo.png', author: 'GameSyte', tags: generateTags('Eaglercraft 1.5.2'), aiHint: generateAiHint('Eaglercraft 1.5.2') },
    { id: 'fridaynightfunkin', title: 'Friday Night Funkin', src: 'https://gamesyte.github.io/fridaynightfunkin/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/fridaynightfunkin/fnf-icon.jpg', author: 'GameSyte', tags: generateTags('Friday Night Funkin'), aiHint: generateAiHint('Friday Night Funkin') },
    { id: 'worldshardestgame', title: 'Worlds Hardest Game', src: 'https://gamesyte.github.io/worldshardestgame/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/worldshardestgame/icon.png', author: 'GameSyte', tags: generateTags('Worlds Hardest Game'), aiHint: generateAiHint('Worlds Hardest Game') },
    { id: 'gba', title: 'GBA Emulator', src: 'https://gamesyte.github.io/gba/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/gba/icon.png', author: 'GameSyte', tags: generateTags('GBA Emulator'), aiHint: generateAiHint('GBA Emulator') },
    { id: 'celeste', title: 'Celeste', src: 'https://gamesyte.github.io/celeste/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/celeste/icon.png', author: 'GameSyte', tags: generateTags('Celeste'), aiHint: generateAiHint('Celeste') },
    { id: 'mario', title: 'Mario', src: 'https://gamesyte.github.io/mario/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/mario/icon.png', author: 'GameSyte', tags: generateTags('Mario'), aiHint: generateAiHint('Mario') },
    { id: '60sburgerrun', title: '60s Burger Run', src: 'https://gamesyte.github.io/60sburgerrun/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/60sburgerrun/icon.png', author: 'GameSyte', tags: generateTags('60s Burger Run'), aiHint: generateAiHint('60s Burger Run') },
    { id: 'cluster-rush', title: 'Cluster Rush', src: 'https://gamesyte.github.io/cluster-rush/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/cluster-rush/icon.jpg', author: 'GameSyte', tags: generateTags('Cluster Rush'), aiHint: generateAiHint('Cluster Rush') },
    { id: 'vex3', title: 'Vex 3', src: 'https://gamesyte.github.io/vex3/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/vex3/icon.png', author: 'GameSyte', tags: generateTags('Vex 3'), aiHint: generateAiHint('Vex 3') },
    { id: 'adventure-capitalist', title: 'Adventure Capitalist', src: 'https://gamesyte.github.io/adventure-capitalist/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/adventure-capitalist/logo.webp', author: 'GameSyte', tags: generateTags('Adventure Capitalist'), aiHint: generateAiHint('Adventure Capitalist') },
    { id: 'btd3', title: 'Bloons Tower Defense 3', src: 'https://gamesyte.github.io/btd3/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/btd3/icon.png', author: 'GameSyte', tags: generateTags('Bloons Tower Defense 3'), aiHint: generateAiHint('Bloons Tower Defense 3') },
    { id: 'avalanche', title: 'Avalanche', src: 'https://gamesyte.github.io/avalanche/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/avalanche/icon.png', author: 'GameSyte', tags: generateTags('Avalanche'), aiHint: generateAiHint('Avalanche') },
    { id: 'slope', title: 'Slope', src: 'https://gamesyte.github.io/slope/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/slope/slope4.jpeg', author: 'GameSyte', tags: generateTags('Slope'), aiHint: generateAiHint('Slope') },
    { id: 'cell-machine', title: 'Cell Machine', src: 'https://gamesyte.github.io/cell-machine/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/cell-machine/img/icon.png', author: 'GameSyte', tags: generateTags('Cell Machine'), aiHint: generateAiHint('Cell Machine') },
    { id: 'run2', title: 'Run 2', src: 'https://gamesyte.github.io/run2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/run2/icon.jpg', author: 'GameSyte', tags: generateTags('Run 2'), aiHint: generateAiHint('Run 2') },
    { id: 'vex5', title: 'Vex 5', src: 'https://gamesyte.github.io/vex5/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/vex5/icon.png', author: 'GameSyte', tags: generateTags('Vex 5'), aiHint: generateAiHint('Vex 5') },
    { id: 'vex4', title: 'Vex 4', src: 'https://gamesyte.github.io/vex4/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/vex4/vex4.png', author: 'GameSyte', tags: generateTags('Vex 4'), aiHint: generateAiHint('Vex 4') },
    { id: 'vex2', title: 'Vex 2', src: 'https://gamesyte.github.io/vex2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/vex2/icon.png', author: 'GameSyte', tags: generateTags('Vex 2'), aiHint: generateAiHint('Vex 2') },
    { id: 'crossyroad', title: 'Crossy Road', src: 'https://gamesyte.github.io/crossyroad/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/crossyroad/chicken.png', author: 'GameSyte', tags: generateTags('Crossy Road'), aiHint: generateAiHint('Crossy Road') },
    { id: 'wallsmash', title: 'Wall Smash', src: 'https://gamesyte.github.io/wallsmash/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/wallsmash/icon.png', author: 'GameSyte', tags: generateTags('Wall Smash'), aiHint: generateAiHint('Wall Smash') },
    { id: 'death-run-3d', title: 'Death Run 3D', src: 'https://gamesyte.github.io/death-run-3d/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/death-run-3d/img/death.png', author: 'GameSyte', tags: generateTags('Death Run 3D'), aiHint: generateAiHint('Death Run 3D') },
    { id: 'gunmayhem2', title: 'Gun Mayhem 2', src: 'https://gamesyte.github.io/gunmayhem2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/gunmayhem2/icon.png', author: 'GameSyte', tags: generateTags('Gun Mayhem 2'), aiHint: generateAiHint('Gun Mayhem 2') },
    { id: 'circloo', title: 'CircloO', src: 'https://gamesyte.github.io/circloo/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/circloo/icon.png', author: 'GameSyte', tags: generateTags('CircloO'), aiHint: generateAiHint('CircloO') },
    { id: 'vex', title: 'Vex', src: 'https://gamesyte.github.io/vex/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/vex/icon.png', author: 'GameSyte', tags: generateTags('Vex'), aiHint: generateAiHint('Vex') },
    { id: 'stack', title: 'Stack', src: 'https://gamesyte.github.io/stack/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/stack/icon.png', author: 'GameSyte', tags: generateTags('Stack'), aiHint: generateAiHint('Stack') },
    { id: 'xx142-b2.exe', title: 'xx142-b2.exe', src: 'https://gamesyte.github.io/xx142-b2.exe/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/xx142-b2.exe/icon.png', author: 'GameSyte', tags: generateTags('xx142-b2.exe'), aiHint: generateAiHint('xx142-b2.exe') },
    { id: 'paperio', title: 'paper.io', src: 'https://gamesyte.github.io/paperio/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/paperio/icon.png', author: 'GameSyte', tags: generateTags('paper.io'), aiHint: generateAiHint('paper.io') },
    { id: 'chibiknight', title: 'Chibi Knight', src: 'https://gamesyte.github.io/chibiknight/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/chibiknight/icon.png', author: 'GameSyte', tags: generateTags('Chibi Knight'), aiHint: generateAiHint('Chibi Knight') },
    { id: '1v1lol', title: '1v1.lol', src: 'https://gamesyte.github.io/1v1lol/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/1v1lol/splash.png', author: 'GameSyte', tags: generateTags('1v1.lol'), aiHint: generateAiHint('1v1.lol') },
    { id: 'dino', title: 'Dino', src: 'https://gamesyte.github.io/dino/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/dino/icon.png', author: 'GameSyte', tags: generateTags('Dino'), aiHint: generateAiHint('Dino') },
    { id: 'turbowarp', title: 'Turbowarp', src: 'https://gamesyte.github.io/turbowarp/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/turbowarp/icon.png', author: 'GameSyte', tags: generateTags('Turbowarp'), aiHint: generateAiHint('Turbowarp') },
    { id: 'tetris', title: 'Tetris', src: 'https://gamesyte.github.io/tetris/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/tetris/icon.png', author: 'GameSyte', tags: generateTags('Tetris'), aiHint: generateAiHint('Tetris') },
    { id: 'geometrydash', title: 'Geometry Dash', src: 'https://gamesyte.github.io/geometrydash/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/geometrydash/icon.png', author: 'GameSyte', tags: generateTags('Geometry Dash'), aiHint: generateAiHint('Geometry Dash') },
    { id: 'sand', title: 'Sand Game', src: 'https://gamesyte.github.io/sand/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/sand/icon.png', author: 'GameSyte', tags: generateTags('Sand Game'), aiHint: generateAiHint('Sand Game') },
    { id: 'dante', title: 'Dante', src: 'https://gamesyte.github.io/dante/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/dante/icon.png', author: 'GameSyte', tags: generateTags('Dante'), aiHint: generateAiHint('Dante') },
    { id: 'wordle', title: 'Wordle', src: 'https://gamesyte.github.io/wordle/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/wordle/icon.png', author: 'GameSyte', tags: generateTags('Wordle'), aiHint: generateAiHint('Wordle') },
    { id: 'offlineparadise', title: 'Offline Paradise', src: 'https://gamesyte.github.io/offlineparadise/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/offlineparadise/icon.png', author: 'GameSyte', tags: generateTags('Offline Paradise'), aiHint: generateAiHint('Offline Paradise') },
    { id: '2048', title: '2048', src: 'https://gamesyte.github.io/2048/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/2048/icon.png', author: 'GameSyte', tags: generateTags('2048'), aiHint: generateAiHint('2048') },
    { id: 'doodlejump', title: 'Doodle Jump', src: 'https://gamesyte.github.io/doodlejump/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/doodlejump/icon.png', author: 'GameSyte', tags: generateTags('Doodle Jump'), aiHint: generateAiHint('Doodle Jump') },
    { id: 'weavesilk', title: 'Weave Silk', src: 'https://gamesyte.github.io/weavesilk/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/weavesilk/icon.png', author: 'GameSyte', tags: generateTags('Weave Silk'), aiHint: generateAiHint('Weave Silk') },
    { id: 'supermeatboy', title: 'Super Meat Boy', src: 'https://gamesyte.github.io/supermeatboy/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/supermeatboy/icon.png', author: 'GameSyte', tags: generateTags('Super Meat Boy'), aiHint: generateAiHint('Super Meat Boy') },
    { id: 'vex6', title: 'Vex 6', src: 'https://gamesyte.github.io/vex6/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/vex6/icon.png', author: 'GameSyte', tags: generateTags('Vex 6'), aiHint: generateAiHint('Vex 6') },
    { id: 'fluidsim', title: 'WebGL Fluid Sim', src: 'https://gamesyte.github.io/fluidsim/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/fluidsim/icon.png', author: 'GameSyte', tags: generateTags('WebGL Fluid Sim'), aiHint: generateAiHint('WebGL Fluid Sim') },
    { id: 'basketball-stars', title: 'Basketball Stars', src: 'https://gamesyte.github.io/basketball-stars/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/basketball-stars/icon.png', author: 'GameSyte', tags: generateTags('Basketball Stars'), aiHint: generateAiHint('Basketball Stars') },
    { id: 'osu', title: 'osu!', src: 'https://gamesyte.github.io/osu/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/osu/icon.png', author: 'GameSyte', tags: generateTags('osu!'), aiHint: generateAiHint('osu!') },
    { id: 'cookieclicker', title: 'Cookie Clicker', src: 'https://gamesyte.github.io/cookieclicker/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/cookieclicker/img/perfectCookie.png', author: 'GameSyte', tags: generateTags('Cookie Clicker'), aiHint: generateAiHint('Cookie Clicker') },
    { id: 'superhot', title: 'Superhot', src: 'https://gamesyte.github.io/superhot/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/superhot/icon.png', author: 'GameSyte', tags: generateTags('Superhot'), aiHint: generateAiHint('Superhot') },
    { id: 'supermario64', title: 'Super Mario 64', src: 'https://gamesyte.github.io/supermario64/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/supermario64/icon.png', author: 'GameSyte', tags: generateTags('Super Mario 64'), aiHint: generateAiHint('Super Mario 64') },
    { id: 'gunmayhemredux', title: 'Gun Mayhem Redux', src: 'https://gamesyte.github.io/gunmayhemredux/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/gunmayhemredux/icon.png', author: 'GameSyte', tags: generateTags('Gun Mayhem Redux'), aiHint: generateAiHint('Gun Mayhem Redux') },
    { id: 'iwbtc', title: 'I Wanna Be Thy Copy', src: 'https://gamesyte.github.io/iwbtc/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/iwbtc/icon.png', author: 'GameSyte', tags: generateTags('I Wanna Be Thy Copy'), aiHint: generateAiHint('I Wanna Be Thy Copy') },
    { id: 'hexgl', title: 'HexGL', src: 'https://gamesyte.github.io/hexgl/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/hexgl/icon_128.png', author: 'GameSyte', tags: generateTags('HexGL'), aiHint: generateAiHint('HexGL') },
    { id: 'championisland', title: 'Champion Island', src: 'https://gamesyte.github.io/championisland/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/championisland/icon.png', author: 'GameSyte', tags: generateTags('Champion Island'), aiHint: generateAiHint('Champion Island') },
    { id: 'learntofly', title: 'Learn to Fly', src: 'https://gamesyte.github.io/learntofly/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/learntofly/icon.png', author: 'GameSyte', tags: generateTags('Learn to Fly'), aiHint: generateAiHint('Learn to Fly') },
    { id: 'wordlebot', title: 'Wordle Bot', src: 'https://gamesyte.github.io/wordlebot/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/wordlebot/icon.png', author: 'GameSyte', tags: generateTags('Wordle Bot'), aiHint: generateAiHint('Wordle Bot') },
    { id: 'cuttherope', title: 'Cut The Rope', src: 'https://gamesyte.github.io/cuttherope/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/cuttherope/icon.png', author: 'GameSyte', tags: generateTags('Cut The Rope'), aiHint: generateAiHint('Cut The Rope') },
    { id: 'chess', title: 'Chess', src: 'https://gamesyte.github.io/chess/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/chess/icon.png', author: 'GameSyte', tags: generateTags('Chess'), aiHint: generateAiHint('Chess') },
    { id: 'flappybird', title: 'Flappy Bird', src: 'https://gamesyte.github.io/flappybird/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/flappybird/icon.png', author: 'GameSyte', tags: generateTags('Flappy Bird'), aiHint: generateAiHint('Flappy Bird') },
    { id: 'lowsadventures2', title: 'Lows Adventures 2', src: 'https://gamesyte.github.io/lowsadventures2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/lowsadventures2/icon.png', author: 'GameSyte', tags: generateTags('Lows Adventures 2'), aiHint: generateAiHint('Lows Adventures 2') },
    { id: 'drift-boss', title: 'Drift Boss', src: 'https://gamesyte.github.io/drift-boss/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/drift-boss/icon.png', author: 'GameSyte', tags: generateTags('Drift Boss'), aiHint: generateAiHint('Drift Boss') },
    { id: 'fireboywatergirl', title: 'Fireboy & Watergirl 1', src: 'https://gamesyte.github.io/fireboywatergirl/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/fireboywatergirl/icon.png', author: 'GameSyte', tags: generateTags('Fireboy & Watergirl 1'), aiHint: generateAiHint('Fireboy & Watergirl 1') },
    { id: 'gunmayhem', title: 'Gun Mayhem', src: 'https://gamesyte.github.io/gunmayhem/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/gunmayhem/icon.png', author: 'GameSyte', tags: generateTags('Gun Mayhem'), aiHint: generateAiHint('Gun Mayhem') },
    { id: 'ducklife4', title: 'Duck Life 4', src: 'https://gamesyte.github.io/ducklife4/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/ducklife4/icon.png', author: 'GameSyte', tags: generateTags('Duck Life 4'), aiHint: generateAiHint('Duck Life 4') },
    { id: 'achieveunlocked', title: 'Achievement Unlocked', src: 'https://gamesyte.github.io/achieveunlocked/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/achieveunlocked/icon.png', author: 'GameSyte', tags: generateTags('Achievement Unlocked'), aiHint: generateAiHint('Achievement Unlocked') },
    { id: 'achieveunlocked2', title: 'Achievement Unlocked 2', src: 'https://gamesyte.github.io/achieveunlocked2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/achieveunlocked2/icon.png', author: 'GameSyte', tags: generateTags('Achievement Unlocked 2'), aiHint: generateAiHint('Achievement Unlocked 2') },
    { id: 'thisistheonlylevel', title: 'This Is The Only Level', src: 'https://gamesyte.github.io/thisistheonlylevel/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/thisistheonlylevel/logo.png', author: 'GameSyte', tags: generateTags('This Is The Only Level'), aiHint: generateAiHint('This Is The Only Level') },
    { id: 'thisistheonlylevel2', title: 'This Is The Only Level 2', src: 'https://gamesyte.github.io/thisistheonlylevel2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/thisistheonlylevel2/icon.png', author: 'GameSyte', tags: generateTags('This Is The Only Level 2'), aiHint: generateAiHint('This Is The Only Level 2') },
    { id: 'bitlife', title: 'Bitlife', src: 'https://gamesyte.github.io/bitlife/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/bitlife/bitlife.png', author: 'GameSyte', tags: generateTags('Bitlife'), aiHint: generateAiHint('Bitlife') },
    { id: 'ducklife1', title: 'Duck Life 1', src: 'https://gamesyte.github.io/ducklife1/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/ducklife1/ducklife1.png', author: 'GameSyte', tags: generateTags('Duck Life 1'), aiHint: generateAiHint('Duck Life 1') },
    { id: 'ducklife2', title: 'Duck Life 2', src: 'https://gamesyte.github.io/ducklife2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/ducklife2/ducklife2.png', author: 'GameSyte', tags: generateTags('Duck Life 2'), aiHint: generateAiHint('Duck Life 2') },
    { id: 'ducklife3', title: 'Duck Life 3', src: 'https://gamesyte.github.io/ducklife3/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/ducklife3/ducklife3.png', author: 'GameSyte', tags: generateTags('Duck Life 3'), aiHint: generateAiHint('Duck Life 3') },
    { id: 'ovo', title: 'ovo', src: 'https://gamesyte.github.io/ovo/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/ovo/ovo3.png', author: 'GameSyte', tags: generateTags('ovo'), aiHint: generateAiHint('ovo') },
    { id: 'thereisnogame', title: 'There Is No Game', src: 'https://gamesyte.github.io/thereisnogame/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/thereisnogame/icon-256.png', author: 'GameSyte', tags: generateTags('There Is No Game'), aiHint: generateAiHint('There Is No Game') },
    { id: 'universal-paperclips', title: 'Universal Paperclips', src: 'https://gamesyte.github.io/universal-paperclips/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/universal-paperclips/universal-paperclips.png', author: 'GameSyte', tags: generateTags('Universal Paperclips'), aiHint: generateAiHint('Universal Paperclips') },
    { id: 'win11', title: 'Windows 11', src: 'https://gamesyte.github.io/win11/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/win11/favicon.png', author: 'GameSyte', tags: generateTags('Windows 11'), aiHint: generateAiHint('Windows 11') },
    { id: 'learntofly2', title: 'Learn to Fly 2', src: 'https://gamesyte.github.io/learntofly2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/learntofly2/logo.jpg', author: 'GameSyte', tags: generateTags('Learn to Fly 2'), aiHint: generateAiHint('Learn to Fly 2') },
    { id: 'worldhardestgame2', title: 'Worlds Hardest Game 2', src: 'https://gamesyte.github.io/worldhardestgame2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/worldhardestgame2/the-worlds-hardest-game-2.jpg', author: 'GameSyte', tags: generateTags('Worlds Hardest Game 2'), aiHint: generateAiHint('Worlds Hardest Game 2') },
    { id: 'vex7', title: 'Vex 7', src: 'https://gamesyte.github.io/vex7/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/vex7/icon.jpeg', author: 'GameSyte', tags: generateTags('Vex 7'), aiHint: generateAiHint('Vex 7') },
    { id: 'slope-ball', title: 'Slope Ball', src: 'https://gamesyte.github.io/slope-ball/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/slope-ball/icon.jpg', author: 'GameSyte', tags: generateTags('Slope Ball'), aiHint: generateAiHint('Slope Ball') },
    { id: 'slope2', title: 'Slope 2', src: 'https://gamesyte.github.io/slope2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/slope2/slope-2-logo.png', author: 'GameSyte', tags: generateTags('Slope 2'), aiHint: generateAiHint('Slope 2') },
    { id: 'learntoflyidle', title: 'Learn to Fly Idle', src: 'https://gamesyte.github.io/learntoflyidle/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/learntoflyidle/icon.jpg', author: 'GameSyte', tags: generateTags('Learn to Fly Idle'), aiHint: generateAiHint('Learn to Fly Idle') },
    { id: 'redball4', title: 'Red Ball 4', src: 'https://gamesyte.github.io/redball4/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/redball4/redball4.webp', author: 'GameSyte', tags: generateTags('Red Ball 4'), aiHint: generateAiHint('Red Ball 4') },
    { id: 'redball4vol3', title: 'Red Ball 4 Vol 3', src: 'https://gamesyte.github.io/redball4vol3/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/redball4vol3/redball4vol3.webp', author: 'GameSyte', tags: generateTags('Red Ball 4 Vol 3'), aiHint: generateAiHint('Red Ball 4 Vol 3') },
    { id: 'redball4vol2', title: 'Red Ball 4 Vol 2', src: 'https://gamesyte.github.io/redball4vol2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/redball4vol2/redball4vol2.webp', author: 'GameSyte', tags: generateTags('Red Ball 4 Vol 2'), aiHint: generateAiHint('Red Ball 4 Vol 2') },
    { id: 'redball3', title: 'Red Ball 3', src: 'https://gamesyte.github.io/redball3/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/redball3/redball3.png', author: 'GameSyte', tags: generateTags('Red Ball 3'), aiHint: generateAiHint('Red Ball 3') },
    { id: 'snake', title: 'Snake', src: 'https://gamesyte.github.io/snake/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/snake/snake.png', author: 'GameSyte', tags: generateTags('Snake'), aiHint: generateAiHint('Snake') },
    { id: 'pacman', title: 'Pacman', src: 'https://gamesyte.github.io/pacman/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/pacman/icon.png', author: 'GameSyte', tags: generateTags('Pacman'), aiHint: generateAiHint('Pacman') },
    { id: 'colorswitch', title: 'Color Switch', src: 'https://gamesyte.github.io/colorswitch/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/colorswitch/colorswitch.png', author: 'GameSyte', tags: generateTags('Color Switch'), aiHint: generateAiHint('Color Switch') },
    { id: 'halloween2016', title: 'Halloween 2016', src: 'https://gamesyte.github.io/halloween2016/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/halloween2016/logo.png', author: 'GameSyte', tags: generateTags('Halloween 2016'), aiHint: generateAiHint('Halloween 2016') },
    { id: 'gamemaker', title: 'Game Maker Doodle', src: 'https://gamesyte.github.io/gamemaker/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/gamemaker/images.jpeg', author: 'GameSyte', tags: generateTags('Game Maker Doodle'), aiHint: generateAiHint('Game Maker Doodle') },
    { id: 'theimpossiblegame', title: 'The Impossible Game', src: 'https://gamesyte.github.io/theimpossiblegame/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/theimpossiblegame/image.jpg', author: 'GameSyte', tags: generateTags('The Impossible Game'), aiHint: generateAiHint('The Impossible Game') },
    { id: 'papasfreezeria', title: 'Papas Freezeria', src: 'https://gamesyte.github.io/papasfreezeria/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/papasfreezeria/images.jpeg', author: 'GameSyte', tags: generateTags('Papas Freezeria'), aiHint: generateAiHint('Papas Freezeria') },
    { id: 'papaspizzeria', title: 'Papas Pizzeria', src: 'https://gamesyte.github.io/papaspizzeria/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/papaspizzeria/images.jpeg', author: 'GameSyte', tags: generateTags('Papas Pizzeria'), aiHint: generateAiHint('Papas Pizzeria') },
    { id: 'idlebreakout', title: 'Idle Breakout', src: 'https://gamesyte.github.io/idlebreakout/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/idlebreakout/image.png', author: 'GameSyte', tags: generateTags('Idle Breakout'), aiHint: generateAiHint('Idle Breakout') },
    { id: 'stickman-hook', title: 'Stickman Hook', src: 'https://gamesyte.github.io/stickman-hook/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/stickman-hook/icon.jpg', author: 'GameSyte', tags: generateTags('Stickman Hook'), aiHint: generateAiHint('Stickman Hook') },
    { id: 'drifthunters', title: 'Drift Hunters', src: 'https://gamesyte.github.io/drifthunters/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/drifthunters/icon.png', author: 'GameSyte', tags: generateTags('Drift Hunters'), aiHint: generateAiHint('Drift Hunters') },
    { id: 'rocketleague', title: 'Rocket League', src: 'https://gamesyte.github.io/rocketleague/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/rocketleague/splash.webp', author: 'GameSyte', tags: generateTags('Rocket League'), aiHint: generateAiHint('Rocket League') },
    { id: 'littlealchemy', title: 'Little Alchemy', src: 'https://gamesyte.github.io/littlealchemy/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/littlealchemy/images/192-alpha.png', author: 'GameSyte', tags: generateTags('Little Alchemy'), aiHint: generateAiHint('Little Alchemy') },
    { id: 'retrobowl', title: 'Retro Bowl', src: 'https://gamesyte.github.io/retrobowl/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/retrobowl/img/icon.jpg', author: 'GameSyte', tags: generateTags('Retro Bowl'), aiHint: generateAiHint('Retro Bowl') },
    { id: 'tunnelrush', title: 'Tunnel Rush', src: 'https://gamesyte.github.io/tunnelrush/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/tunnelrush/tunnel.jpg', author: 'GameSyte', tags: generateTags('Tunnel Rush'), aiHint: generateAiHint('Tunnel Rush') },
    { id: 'motox3m', title: 'Moto X3M', src: 'https://gamesyte.github.io/motox3m/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/motox3m/splash.jpg', author: 'GameSyte', tags: generateTags('Moto X3M'), aiHint: generateAiHint('Moto X3M') },
    { id: 'motox3m-winter', title: 'Moto X3M Winter', src: 'https://gamesyte.github.io/motox3m-winter/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/motox3m-winter/download.jpeg', author: 'GameSyte', tags: generateTags('Moto X3M Winter'), aiHint: generateAiHint('Moto X3M Winter') },
    { id: 'motox3m-pool', title: 'Moto X3M Pool Party', src: 'https://gamesyte.github.io/motox3m-pool/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/motox3m-pool/splash.jpg', author: 'GameSyte', tags: generateTags('Moto X3M Pool Party'), aiHint: generateAiHint('Moto X3M Pool Party') },
    { id: 'fnaf', title: 'Five Nights at Freddy\'s', src: 'https://gamesyte.github.io/fnaf/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/fnaf/splash.jpg', author: 'GameSyte', tags: generateTags('Five Nights at Freddy\'s'), aiHint: generateAiHint('Five Nights at Freddy\'s') },
    { id: 'burritobison', title: 'Burrito Bison', src: 'https://gamesyte.github.io/burritobison/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/burritobison/Build/logo.png', author: 'GameSyte', tags: generateTags('Burrito Bison'), aiHint: generateAiHint('Burrito Bison') },
    { id: 'cuttherope-holiday', title: 'Cut The Rope Holday', src: 'https://gamesyte.github.io/cuttherope-holiday/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/cuttherope-holiday/Holiday_Gift.webp', author: 'GameSyte', tags: generateTags('Cut The Rope Holday'), aiHint: generateAiHint('Cut The Rope Holday') },
    { id: 'helixjump', title: 'Helix Jump', src: 'https://gamesyte.github.io/helixjump/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/helixjump/gameIcon.png', author: 'GameSyte', tags: generateTags('Helix Jump'), aiHint: generateAiHint('Helix Jump') },
    { id: 'clickerheroes', title: 'Clicker Heroes', src: 'https://gamesyte.github.io/clickerheroes/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/clickerheroes/clicker-heroes.png', author: 'GameSyte', tags: generateTags('Clicker Heroes'), aiHint: generateAiHint('Clicker Heroes') },
    { id: 'jetpackjoyride', title: 'Jetpack Joyride', src: 'https://gamesyte.github.io/jetpackjoyride/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/jetpackjoyride/logo.jpeg', author: 'GameSyte', tags: generateTags('Jetpack Joyride'), aiHint: generateAiHint('Jetpack Joyride') },
    { id: 'fruitninja', title: 'Fruit Ninja', src: 'https://gamesyte.github.io/fruitninja/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/fruitninja/FruitNinjaTeaser.jpg', author: 'GameSyte', tags: generateTags('Fruit Ninja'), aiHint: generateAiHint('Fruit Ninja') },
    { id: 'tron', title: 'Tron', src: 'https://gamesyte.github.io/tron/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/tron/icon.png', author: 'GameSyte', tags: generateTags('Tron'), aiHint: generateAiHint('Tron') },
    { id: 'thirtydollarwebsite', title: 'Thirty Dollar Website', src: 'https://gamesyte.github.io/thirtydollarwebsite/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/thirtydollarwebsite/assets/🗿.png', author: 'GameSyte', tags: generateTags('Thirty Dollar Website'), aiHint: generateAiHint('Thirty Dollar Website') },
    { id: 'ngon', title: 'n-gon', src: 'https://gamesyte.github.io/ngon/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/ngon/favicon.ico', author: 'GameSyte', tags: generateTags('n-gon'), aiHint: generateAiHint('n-gon') },
    { id: 'subway-surfers-ny', title: 'Subway Surfers', src: 'https://gamesyte.github.io/subway-surfers-ny/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/subway-surfers-ny/NewYorkIcon.png', author: 'GameSyte', tags: generateTags('Subway Surfers'), aiHint: generateAiHint('Subway Surfers') },
    { id: 'madalincars', title: 'Madalin Cars', src: 'https://gamesyte.github.io/madalincars/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/madalincars/icon.png', author: 'GameSyte', tags: generateTags('Madalin Cars'), aiHint: generateAiHint('Madalin Cars') },
    { id: 'run3', title: 'Run 3', src: 'https://gamesyte.github.io/run3/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/run3/icon.jpeg', author: 'GameSyte', tags: generateTags('Run 3'), aiHint: generateAiHint('Run 3') },
    { id: 'dragonballdevolution', title: 'Dragon Ball Devolution', src: 'https://gamesyte.github.io/dragonballdevolution/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/dragonballdevolution/images.jpeg', author: 'GameSyte', tags: generateTags('Dragon Ball Devolution'), aiHint: generateAiHint('Dragon Ball Devolution') },
    { id: 'run', title: 'Run', src: 'https://gamesyte.github.io/run/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/run/icon.jpeg', author: 'GameSyte', tags: generateTags('Run'), aiHint: generateAiHint('Run') },
    { id: 'supersmashflash', title: 'Super Smash Flash', src: 'https://gamesyte.github.io/supersmashflash/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/supersmashflash/ssf.jpg', author: 'GameSyte', tags: generateTags('Super Smash Flash'), aiHint: generateAiHint('Super Smash Flash') },
    { id: 'stickmanclimb', title: 'Stickman Climb', src: 'https://gamesyte.github.io/stickmanclimb/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/stickmanclimb/icon.avif', author: 'GameSyte', tags: generateTags('Stickman Climb'), aiHint: generateAiHint('Stickman Climb') },
    { id: 'getawayshooter', title: 'Getaway Shooter', src: 'https://gamesyte.github.io/getawayshooter/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/getawayshooter/Untitled.jpeg', author: 'GameSyte', tags: generateTags('Getaway Shooter'), aiHint: generateAiHint('Getaway Shooter') },
    { id: 'riddleschool', title: 'Riddle School', src: 'https://gamesyte.github.io/riddleschool/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/riddleschool/RiddleSchool2.png', author: 'GameSyte', tags: generateTags('Riddle School'), aiHint: generateAiHint('Riddle School') },
    { id: 'riddleschool2', title: 'Riddle School 2', src: 'https://gamesyte.github.io/riddleschool2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/riddleschool2/icon.png', author: 'GameSyte', tags: generateTags('Riddle School 2'), aiHint: generateAiHint('Riddle School 2') },
    { id: 'riddleschool3', title: 'Riddle School 3', src: 'https://gamesyte.github.io/riddleschool3/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/riddleschool3/riddle-school-3.webp', author: 'GameSyte', tags: generateTags('Riddle School 3'), aiHint: generateAiHint('Riddle School 3') },
    { id: 'riddleschool4', title: 'Riddle School 4', src: 'https://gamesyte.github.io/riddleschool4/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/riddleschool4/Untitled.jpeg', author: 'GameSyte', tags: generateTags('Riddle School 4'), aiHint: generateAiHint('Riddle School 4') },
    { id: 'riddleschool5', title: 'Riddle School 5', src: 'https://gamesyte.github.io/riddleschool5/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/riddleschool5/Untitled.jpeg', author: 'GameSyte', tags: generateTags('Riddle School 5'), aiHint: generateAiHint('Riddle School 5') },
    { id: 'riddleschooltransfer', title: 'Riddle Transfer', src: 'https://gamesyte.github.io/riddleschooltransfer/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/riddleschooltransfer/Untitled.jpeg', author: 'GameSyte', tags: generateTags('Riddle Transfer'), aiHint: generateAiHint('Riddle Transfer') },
    { id: 'riddleschooltransfer2', title: 'Riddle Transfer 2', src: 'https://gamesyte.github.io/riddleschooltransfer2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/riddleschooltransfer2/aUntitled.jpeg', author: 'GameSyte', tags: generateTags('Riddle Transfer 2'), aiHint: generateAiHint('Riddle Transfer 2') },
    { id: 'zombocalypse', title: 'Zombocalypse', src: 'https://gamesyte.github.io/zombocalypse/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/zombocalypse/zombocalypse-2.webp', author: 'GameSyte', tags: generateTags('Zombocalypse'), aiHint: generateAiHint('Zombocalypse') },
    { id: 'papasburgeria', title: 'Papas Burgeria', src: 'https://gamesyte.github.io/papasburgeria/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/papasburgeria/images.jpeg', author: 'GameSyte', tags: generateTags('Papas Burgeria'), aiHint: generateAiHint('Papas Burgeria') },
    { id: 'ducklife5', title: 'Duck Life 5', src: 'https://gamesyte.github.io/ducklife5/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/ducklife5/ducklife5.png', author: 'GameSyte', tags: generateTags('Duck Life 5'), aiHint: generateAiHint('Duck Life 5') },
    { id: 'ducklife6', title: 'Duck Life 6', src: 'https://gamesyte.github.io/ducklife6/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/ducklife6/ducklife5.png', author: 'GameSyte', tags: generateTags('Duck Life 6'), aiHint: generateAiHint('Duck Life 6') },
    { id: 'webretro', title: 'webretro', src: 'https://gamesyte.github.io/webretro/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/webretro/assets/icons/icon204.png', author: 'GameSyte', tags: generateTags('webretro'), aiHint: generateAiHint('webretro') },
    { id: 'osumania', title: 'osu!mania', src: 'https://gamesyte.github.io/osumania/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/osumania/mania.jpg', author: 'GameSyte', tags: generateTags('osu!mania'), aiHint: generateAiHint('osu!mania') },
    { id: 'fnaf2', title: 'Five Nights at Freddy\'s 2', src: 'https://gamesyte.github.io/fnaf2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/fnaf2/project/splash.webp', author: 'GameSyte', tags: generateTags('Five Nights at Freddy\'s 2'), aiHint: generateAiHint('Five Nights at Freddy\'s 2') },
    { id: 'fnaf3', title: 'Five Nights at Freddy\'s 3', src: 'https://gamesyte.github.io/fnaf3/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/fnaf3/project/splash.webp', author: 'GameSyte', tags: generateTags('Five Nights at Freddy\'s 3'), aiHint: generateAiHint('Five Nights at Freddy\'s 3') },
    { id: 'fnaf4', title: 'Five Nights at Freddy\'s 4', src: 'https://gamesyte.github.io/fnaf4/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/fnaf4/project/splash.webp', author: 'GameSyte', tags: generateTags('Five Nights at Freddy\'s 4'), aiHint: generateAiHint('Five Nights at Freddy\'s 4') },
    { id: 'templerun2', title: 'Temple Run 2', src: 'https://gamesyte.github.io/templerun2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/templerun2/img/icons/icon-128x128.png', author: 'GameSyte', tags: generateTags('Temple Run 2'), aiHint: generateAiHint('Temple Run 2') },
    { id: 'happywheels', title: 'Happy Wheels', src: 'https://gamesyte.github.io/happywheels/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/happywheels/Untitled.jpeg', author: 'GameSyte', tags: generateTags('Happy Wheels'), aiHint: generateAiHint('Happy Wheels') },
    { id: 'fireboywatergirl2', title: 'Fireboy & Watergirl 2', src: 'https://gamesyte.github.io/fireboywatergirl2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/fireboywatergirl2/Untitled.jpeg', author: 'GameSyte', tags: generateTags('Fireboy & Watergirl 2'), aiHint: generateAiHint('Fireboy & Watergirl 2') },
    { id: 'fireboywatergirl3', title: 'Fireboy & Watergirl 3', src: 'https://gamesyte.github.io/fireboywatergirl3/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/fireboywatergirl3/icon.png', author: 'GameSyte', tags: generateTags('Fireboy & Watergirl 3'), aiHint: generateAiHint('Fireboy & Watergirl 3') },
    { id: 'fireboywatergirl4', title: 'Fireboy & Watergirl 4', src: 'https://gamesyte.github.io/fireboywatergirl4/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/fireboywatergirl4/300.jpg', author: 'GameSyte', tags: generateTags('Fireboy & Watergirl 4'), aiHint: generateAiHint('Fireboy & Watergirl 4') },
    { id: 'risehigher', title: 'Rise Higher', src: 'https://gamesyte.github.io/risehigher/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/risehigher/media/graphics/promo/Icons/128x128.png', author: 'GameSyte', tags: generateTags('Rise Higher'), aiHint: generateAiHint('Rise Higher') },
    { id: 'hextris', title: 'Hextris', src: 'https://gamesyte.github.io/hextris/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/hextris/images/icons/apple-touch-152.png', author: 'GameSyte', tags: generateTags('Hextris'), aiHint: generateAiHint('Hextris') },
    { id: 'sprinter', title: 'Sprinter', src: 'https://gamesyte.github.io/sprinter/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/sprinter/icon.jpeg', author: 'GameSyte', tags: generateTags('Sprinter'), aiHint: generateAiHint('Sprinter') },
    { id: 'amazing-rope-police', title: 'Amazing Rope Police', src: 'https://gamesyte.github.io/amazing-rope-police/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/amazing-rope-police/splash.jpeg', author: 'GameSyte', tags: generateTags('Amazing Rope Police'), aiHint: generateAiHint('Amazing Rope Police') },
    { id: 'ruffle', title: 'Ruffle', src: 'https://gamesyte.github.io/ruffle/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/ruffle/favicon-180.png', author: 'GameSyte', tags: generateTags('Ruffle'), aiHint: generateAiHint('Ruffle') },
    { id: 'emulatorjs', title: 'emulatorJS', src: 'https://gamesyte.github.io/emulatorjs/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/emulatorjs/logo.png', author: 'GameSyte', tags: generateTags('emulatorJS'), aiHint: generateAiHint('emulatorJS') },
    { id: 'geometryrash', title: 'Geometry Rash', src: 'https://gamesyte.github.io/geometryrash/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/geometryrash/icon-114.png', author: 'GameSyte', tags: generateTags('Geometry Rash'), aiHint: generateAiHint('Geometry Rash') },
    { id: 'btd', title: 'Bloons Tower Defense', src: 'https://gamesyte.github.io/btd/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/btd/logo.webp', author: 'GameSyte', tags: generateTags('Bloons Tower Defense'), aiHint: generateAiHint('Bloons Tower Defense') },
    { id: 'btd2', title: 'Bloons Tower Defense 2', src: 'https://gamesyte.github.io/btd2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/btd2/logo.webp', author: 'GameSyte', tags: generateTags('Bloons Tower Defense 2'), aiHint: generateAiHint('Bloons Tower Defense 2') },
    { id: 'btd4', title: 'Bloons Tower Defense 4', src: 'https://gamesyte.github.io/btd4/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/btd4/logo.jpg', author: 'GameSyte', tags: generateTags('Bloons Tower Defense 4'), aiHint: generateAiHint('Bloons Tower Defense 4') },
    { id: 'btd6', title: 'Bloons Tower Defense 6', src: 'https://gamesyte.github.io/btd6/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/btd6/uwu.png', author: 'GameSyte', tags: generateTags('Bloons Tower Defense 6'), aiHint: generateAiHint('Bloons Tower Defense 6') },
    { id: 'btd5', title: 'Bloons Tower Defense 5', src: 'https://gamesyte.github.io/btd5/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/btd5/wogo.png', author: 'GameSyte', tags: generateTags('Bloons Tower Defense 5'), aiHint: generateAiHint('Bloons Tower Defense 5') },
    { id: 'lasthorizon', title: 'Last Horizon', src: 'https://gamesyte.github.io/lasthorizon/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/lasthorizon/wogo owo.jpg', author: 'GameSyte', tags: generateTags('Last Horizon'), aiHint: generateAiHint('Last Horizon') },
    { id: '1on1soccer', title: '1 on 1 Soccer', src: 'https://gamesyte.github.io/1on1soccer/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/1on1soccer/logo.jpg', author: 'GameSyte', tags: generateTags('1 on 1 Soccer'), aiHint: generateAiHint('1 on 1 Soccer') },
    { id: 'amongus', title: 'Among Us', src: 'https://gamesyte.github.io/amongus/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/amongus/amgojs]_.png', author: 'GameSyte', tags: generateTags('Among Us'), aiHint: generateAiHint('Among Us') },
    { id: 'badpiggies', title: 'Bad Piggies', src: 'https://gamesyte.github.io/badpiggies/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/badpiggies/badpiggies.png', author: 'GameSyte', tags: generateTags('Bad Piggies'), aiHint: generateAiHint('Bad Piggies') },
    { id: 'sandtrix', title: 'Sandtrix', src: 'https://gamesyte.github.io/sandtrix/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/sandtrix/assets/sprites/appicon.png', author: 'GameSyte', tags: generateTags('Sandtrix'), aiHint: generateAiHint('Sandtrix') },
    { id: 'bloodtournament', title: 'Blood Tournament', src: 'https://gamesyte.github.io/bloodtournament/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/bloodtournament/blood-tournament.jpg', author: 'GameSyte', tags: generateTags('Blood Tournament'), aiHint: generateAiHint('Blood Tournament') },
    { id: 'golddiggerfrvr', title: 'Gold Digger FRVR', src: 'https://gamesyte.github.io/golddiggerfrvr/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/golddiggerfrvr/images.jpeg', author: 'GameSyte', tags: generateTags('Gold Digger FRVR'), aiHint: generateAiHint('Gold Digger FRVR') },
    { id: 'retrobowlcollege', title: 'Retro Bowl College', src: 'https://gamesyte.github.io/retrobowlcollege/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/retrobowlcollege/unnamed.png', author: 'GameSyte', tags: generateTags('Retro Bowl College'), aiHint: generateAiHint('Retro Bowl College') },
    { id: 'wbwwb', title: 'We Become What We Behold', src: 'https://gamesyte.github.io/wbwwb/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/wbwwb/wbwwb.webp', author: 'GameSyte', tags: generateTags('We Become What We Behold'), aiHint: generateAiHint('We Become What We Behold') },
    { id: 'nutsim', title: 'Nut Simulator', src: 'https://gamesyte.github.io/nutsim/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/nutsim/images/icon.png', author: 'GameSyte', tags: generateTags('Nut Simulator'), aiHint: generateAiHint('Nut Simulator') },
    { id: 'pokemon', title: 'Pokemon', src: 'https://gamesyte.github.io/pokemon/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/pokemon/logo.jpg', author: 'GameSyte', tags: generateTags('Pokemon'), aiHint: generateAiHint('Pokemon') },
    { id: 'supersmashbros', title: 'Super Smash Bros', src: 'https://gamesyte.github.io/supersmashbros/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/supersmashbros/logo.jpg', author: 'GameSyte', tags: generateTags('Super Smash Bros'), aiHint: generateAiHint('Super Smash Bros') },
    { id: 'skibiditoilet', title: 'Skibidi 1 v 100', src: 'https://gamesyte.github.io/skibiditoilet/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/skibiditoilet/logo.png', author: 'GameSyte', tags: generateTags('Skibidi 1 v 100'), aiHint: generateAiHint('Skibidi 1 v 100') },
    { id: 'drivemad', title: 'Drive Mad', src: 'https://gamesyte.github.io/drivemad/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/drivemad/icons/icon-128.png', author: 'GameSyte', tags: generateTags('Drive Mad'), aiHint: generateAiHint('Drive Mad') },
    { id: 'rooftopsnipers', title: 'Rooftop Snipers', src: 'https://gamesyte.github.io/rooftopsnipers/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/rooftopsnipers/logo.png', author: 'GameSyte', tags: generateTags('Rooftop Snipers'), aiHint: generateAiHint('Rooftop Snipers') },
    { id: 'funnyshooter', title: 'Funny Shooter', src: 'https://gamesyte.github.io/funnyshooter/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/funnyshooter/icon.jpeg', author: 'GameSyte', tags: generateTags('Funny Shooter'), aiHint: generateAiHint('Funny Shooter') },
    { id: 'monkeymart', title: 'Monkey Mart', src: 'https://gamesyte.github.io/monkeymart/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/monkeymart/unnamed.png', author: 'GameSyte', tags: generateTags('Monkey Mart'), aiHint: generateAiHint('Monkey Mart') },
    { id: 'factoryballs', title: 'Factory Balls', src: 'https://gamesyte.github.io/factoryballs/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/factoryballs/fac.png', author: 'GameSyte', tags: generateTags('Factory Balls'), aiHint: generateAiHint('Factory Balls') },
    { id: 'factoryballsforever', title: 'Factory Balls Forever', src: 'https://gamesyte.github.io/factoryballsforever/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/factoryballsforever/fac.png', author: 'GameSyte', tags: generateTags('Factory Balls Forever'), aiHint: generateAiHint('Factory Balls Forever') },
    { id: 'funnyshooter2', title: 'Funny Shooter 2', src: 'https://gamesyte.github.io/funnyshooter2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/funnyshooter2/894abba63a6b23fed823f404831f444f.jpeg', author: 'GameSyte', tags: generateTags('Funny Shooter 2'), aiHint: generateAiHint('Funny Shooter 2') },
    { id: 'badtimesimulator', title: 'Bad Time Simulator', src: 'https://gamesyte.github.io/badtimesimulator/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/badtimesimulator/icon-114.png', author: 'GameSyte', tags: generateTags('Bad Time Simulator'), aiHint: generateAiHint('Bad Time Simulator') },
    { id: 'commodoreclicker', title: 'Commodore 64 Clicker', src: 'https://gamesyte.github.io/commodoreclicker/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/commodoreclicker/test.jpg', author: 'GameSyte', tags: generateTags('Commodore 64 Clicker'), aiHint: generateAiHint('Commodore 64 Clicker') },
    { id: 'stickmanboost', title: 'Stickman Boost', src: 'https://gamesyte.github.io/stickmanboost/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/stickmanboost/base/img1.jpg', author: 'GameSyte', tags: generateTags('Stickman Boost'), aiHint: generateAiHint('Stickman Boost') },
    { id: 'stickmangolf', title: 'Stickman Golf', src: 'https://gamesyte.github.io/stickmangolf/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/stickmangolf/gold.png', author: 'GameSyte', tags: generateTags('Stickman Golf'), aiHint: generateAiHint('Stickman Golf') },
    { id: 'basketbros', title: 'Basket Bros', src: 'https://gamesyte.github.io/basketbros/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/basketbros/thumb.jpg', author: 'GameSyte', tags: generateTags('Basket Bros'), aiHint: generateAiHint('Basket Bros') },
    { id: 'justfalllol', title: 'justfall.lol', src: 'https://gamesyte.github.io/justfalllol/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/justfalllol/unnamed.png', author: 'GameSyte', tags: generateTags('justfall.lol'), aiHint: generateAiHint('justfall.lol') },
    { id: 'dogeminer', title: 'Doge Miner', src: 'https://gamesyte.github.io/dogeminer/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/dogeminer/img/dogeminer_300x300.png', author: 'GameSyte', tags: generateTags('Doge Miner'), aiHint: generateAiHint('Doge Miner') },
    { id: 'soccerrandom', title: 'Soccer Random', src: 'https://gamesyte.github.io/soccerrandom/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/soccerrandom/test.png', author: 'GameSyte', tags: generateTags('Soccer Random'), aiHint: generateAiHint('Soccer Random') },
    { id: 'basketrandom', title: 'Basket Random', src: 'https://gamesyte.github.io/basketrandom/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/basketrandom/test.png', author: 'GameSyte', tags: generateTags('Basket Random'), aiHint: generateAiHint('Basket Random') },
    { id: 'boxingrandom', title: 'Boxing Random', src: 'https://gamesyte.github.io/boxingrandom/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/boxingrandom/512x512.jpg', author: 'GameSyte', tags: generateTags('Boxing Random'), aiHint: generateAiHint('Boxing Random') },
    { id: 'funnymadracing', title: 'Funny Mad Racing', src: 'https://gamesyte.github.io/funnymadracing/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/funnymadracing/logo.webp', author: 'GameSyte', tags: generateTags('Funny Mad Racing'), aiHint: generateAiHint('Funny Mad Racing') },
    { id: 'holeio', title: 'hole.io', src: 'https://gamesyte.github.io/holeio/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/holeio/feature800x470.png', author: 'GameSyte', tags: generateTags('hole.io'), aiHint: generateAiHint('hole.io') },
    { id: 'timeshooter1', title: 'Time Shooter', src: 'https://gamesyte.github.io/timeshooter1/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/timeshooter1/logo.png', author: 'GameSyte', tags: generateTags('Time Shooter'), aiHint: generateAiHint('Time Shooter') },
    { id: 'timeshooter2', title: 'Time Shooter 2', src: 'https://gamesyte.github.io/timeshooter2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/timeshooter2/ts2.jpg', author: 'GameSyte', tags: generateTags('Time Shooter 2'), aiHint: generateAiHint('Time Shooter 2') },
    { id: 'timeshooter3', title: 'Time Shooter 3', src: 'https://gamesyte.github.io/timeshooter3/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/timeshooter3/logo.png', author: 'GameSyte', tags: generateTags('Time Shooter 3'), aiHint: generateAiHint('Time Shooter 3') },
    { id: 'townscaper', title: 'Townscaper', src: 'https://gamesyte.github.io/townscaper/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/townscaper/icon.png', author: 'GameSyte', tags: generateTags('Townscaper'), aiHint: generateAiHint('Townscaper') },
    { id: 'badicecream', title: 'Bad Ice Cream', src: 'https://gamesyte.github.io/badicecream/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/badicecream/bad-ice-cream.png', author: 'GameSyte', tags: generateTags('Bad Ice Cream'), aiHint: generateAiHint('Bad Ice Cream') },
    { id: 'badicecream2', title: 'Bad Ice Cream 2', src: 'https://gamesyte.github.io/badicecream2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/badicecream2/bad-ice-cream-2.png', author: 'GameSyte', tags: generateTags('Bad Ice Cream 2'), aiHint: generateAiHint('Bad Ice Cream 2') },
    { id: 'badicecream3', title: 'Bad Ice Cream 3', src: 'https://gamesyte.github.io/badicecream3/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/badicecream3/bad-ice-cream-3.png', author: 'GameSyte', tags: generateTags('Bad Ice Cream 3'), aiHint: generateAiHint('Bad Ice Cream 3') },
    { id: 'bobtherobber2', title: 'Bob the Robber 2', src: 'https://gamesyte.github.io/bobtherobber2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/bobtherobber2/icon.png', author: 'GameSyte', tags: generateTags('Bob the Robber 2'), aiHint: generateAiHint('Bob the Robber 2') },
    { id: 'boxingphysics2', title: 'Boxing Physics 2', src: 'https://gamesyte.github.io/boxingphysics2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/boxingphysics2/icon.png', author: 'GameSyte', tags: generateTags('Boxing Physics 2'), aiHint: generateAiHint('Boxing Physics 2') },
    { id: 'burgerandfrights', title: 'Burger and Frights', src: 'https://gamesyte.github.io/burgerandfrights/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/burgerandfrights/icon.png', author: 'GameSyte', tags: generateTags('Burger and Frights'), aiHint: generateAiHint('Burger and Frights') },
    { id: 'flippyfish', title: 'Flippy Fish', src: 'https://gamesyte.github.io/flippyfish/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/flippyfish/icon.png', author: 'GameSyte', tags: generateTags('Flippy Fish'), aiHint: generateAiHint('Flippy Fish') },
    { id: 'knifehit', title: 'Knife Hit', src: 'https://gamesyte.github.io/knifehit/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/knifehit/icon.png', author: 'GameSyte', tags: generateTags('Knife Hit'), aiHint: generateAiHint('Knife Hit') },
    { id: 'lazyjump3d', title: 'Lazy Jump 3D', src: 'https://gamesyte.github.io/lazyjump3d/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/lazyjump3d/icon.png', author: 'GameSyte', tags: generateTags('Lazy Jump 3D'), aiHint: generateAiHint('Lazy Jump 3D') },
    { id: 'motox3m-spooky', title: 'Moto X3M Spooky', src: 'https://gamesyte.github.io/motox3m-spooky/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/motox3m-spooky/icon.png', author: 'GameSyte', tags: generateTags('Moto X3M Spooky'), aiHint: generateAiHint('Moto X3M Spooky') },
    { id: 'rooftopsnipers2', title: 'Rooftop Snipers 2', src: 'https://gamesyte.github.io/rooftopsnipers2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/rooftopsnipers2/icon.png', author: 'GameSyte', tags: generateTags('Rooftop Snipers 2'), aiHint: generateAiHint('Rooftop Snipers 2') },
    { id: 'skibiditoiletattack', title: 'Skibidi Toilet Attack', src: 'https://gamesyte.github.io/skibiditoiletattack/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/skibiditoiletattack/logo.png', author: 'GameSyte', tags: generateTags('Skibidi Toilet Attack'), aiHint: generateAiHint('Skibidi Toilet Attack') },
    { id: 'tinyfishing', title: 'Tiny Fishing', src: 'https://gamesyte.github.io/tinyfishing/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/tinyfishing/thumb.png', author: 'GameSyte', tags: generateTags('Tiny Fishing'), aiHint: generateAiHint('Tiny Fishing') },
    { id: 'tu95', title: 'TU-95', src: 'https://gamesyte.github.io/tu95/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/tu95/tu-95.webp', author: 'GameSyte', tags: generateTags('TU-95'), aiHint: generateAiHint('TU-95') },
    { id: 'tu46', title: 'TU-46', src: 'https://gamesyte.github.io/tu46/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/tu46/tu-46.webp', author: 'GameSyte', tags: generateTags('TU-46'), aiHint: generateAiHint('TU-46') },
    { id: 'russiancardriver', title: 'Russian Car Driver', src: 'https://gamesyte.github.io/russiancardriver/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/russiancardriver/russian-car-driver.webp', author: 'GameSyte', tags: generateTags('Russian Car Driver'), aiHint: generateAiHint('Russian Car Driver') },
    { id: 'ocarinaoftime', title: 'Legend of Zelda - Ocarina of Time', src: 'https://gamesyte.github.io/ocarinaoftime/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/ocarinaoftime/oc.jpg', author: 'GameSyte', tags: generateTags('Legend of Zelda - Ocarina of Time'), aiHint: generateAiHint('Legend of Zelda - Ocarina of Time') },
    { id: 'metroidzeromission', title: 'Metroid: Zero Mission', src: 'https://gamesyte.github.io/metroidzeromission/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/metroidzeromission/zero.jpeg', author: 'GameSyte', tags: generateTags('Metroid: Zero Mission'), aiHint: generateAiHint('Metroid: Zero Mission') },
    { id: 'guiltygear', title: 'Guilty Gear', src: 'https://gamesyte.github.io/guiltygear/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/guiltygear/ggx.jpg', author: 'GameSyte', tags: generateTags('Guilty Gear'), aiHint: generateAiHint('Guilty Gear') },
    { id: 'adarkroom', title: 'A Dark Room', src: 'https://gamesyte.github.io/adarkroom/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/adarkroom/favicon.ico', author: 'GameSyte', tags: generateTags('A Dark Room'), aiHint: generateAiHint('A Dark Room') },
    { id: 'fancypantsadventures', title: 'Fancy Pants Adventures', src: 'https://gamesyte.github.io/fancypantsadventures/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/fancypantsadventures/fpa.webp', author: 'GameSyte', tags: generateTags('Fancy Pants Adventures'), aiHint: generateAiHint('Fancy Pants Adventures') },
    { id: 'fancypantsadventures2', title: 'Fancy Pants Adventures 2', src: 'https://gamesyte.github.io/fancypantsadventures2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/fancypantsadventures2/fpa2.avif', author: 'GameSyte', tags: generateTags('Fancy Pants Adventures 2'), aiHint: generateAiHint('Fancy Pants Adventures 2') },
    { id: 'linerider', title: 'Line Rider', src: 'https://gamesyte.github.io/linerider/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/linerider/boosh.png', author: 'GameSyte', tags: generateTags('Line Rider'), aiHint: generateAiHint('Line Rider') },
    { id: 'funnyballgame', title: 'Funny Ball Game', src: 'https://gamesyte.github.io/funnyballgame/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/funnyballgame/ball.jpg', author: 'GameSyte', tags: generateTags('Funny Ball Game'), aiHint: generateAiHint('Funny Ball Game') },
    { id: 'stealingthediamond', title: 'Henry Stickmin - Stealing the Diamond', src: 'https://gamesyte.github.io/stealingthediamond/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/stealingthediamond/diamante.avif', author: 'GameSyte', tags: generateTags('Henry Stickmin - Stealing the Diamond'), aiHint: generateAiHint('Henry Stickmin - Stealing the Diamond') },
    { id: 'breakingthebank', title: 'Henry Stickmin - Breaking the Bank', src: 'https://gamesyte.github.io/breakingthebank/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/breakingthebank/balling.avif', author: 'GameSyte', tags: generateTags('Henry Stickmin - Breaking the Bank'), aiHint: generateAiHint('Henry Stickmin - Breaking the Bank') },
    { id: 'escapingtheprison', title: 'Henry Stickmin - Escaping the Prison', src: 'https://gamesyte.github.io/escapingtheprison/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/escapingtheprison/pwison.avif', author: 'GameSyte', tags: generateTags('Henry Stickmin - Escaping the Prison'), aiHint: generateAiHint('Henry Stickmin - Escaping the Prison') },
    { id: 'fleeingthecomplex', title: 'Henry Stickmin - Fleeing the Complex', src: 'https://gamesyte.github.io/fleeingthecomplex/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/fleeingthecomplex/flee.jpg', author: 'GameSyte', tags: generateTags('Henry Stickmin - Fleeing the Complex'), aiHint: generateAiHint('Henry Stickmin - Fleeing the Complex') },
    { id: 'infiltratingtheairship', title: 'Henry Stickmin - Infiltrating the Airship', src: 'https://gamesyte.github.io/infiltratingtheairship/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/infiltratingtheairship/air.avif', author: 'GameSyte', tags: generateTags('Henry Stickmin - Infiltrating the Airship'), aiHint: generateAiHint('Henry Stickmin - Infiltrating the Airship') },
    { id: 'pandemic', title: 'Pandemic', src: 'https://gamesyte.github.io/pandemic/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/pandemic/sddefault.jpg', author: 'GameSyte', tags: generateTags('Pandemic'), aiHint: generateAiHint('Pandemic') },
    { id: 'pandemic2', title: 'Pandemic 2', src: 'https://gamesyte.github.io/pandemic2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/pandemic2/pan2.webp', author: 'GameSyte', tags: generateTags('Pandemic 2'), aiHint: generateAiHint('Pandemic 2') },
    { id: 'ageofwar', title: 'Age of War', src: 'https://gamesyte.github.io/ageofwar/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/ageofwar/warofage.jpg', author: 'GameSyte', tags: generateTags('Age of War'), aiHint: generateAiHint('Age of War') },
    { id: 'soundboard', title: 'Soundboard', src: 'https://gamesyte.github.io/soundboard/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/soundboard/bleep.png', author: 'GameSyte', tags: generateTags('Soundboard'), aiHint: generateAiHint('Soundboard') },
    { id: 'theimpossiblequiz', title: 'The Impossible Quiz', src: 'https://gamesyte.github.io/theimpossiblequiz/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/theimpossiblequiz/tiq.avif', author: 'GameSyte', tags: generateTags('The Impossible Quiz'), aiHint: generateAiHint('The Impossible Quiz') },
    { id: '2drocketleague', title: '2D Rocket League', src: 'https://gamesyte.github.io/2drocketleague/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/2drocketleague/unnamed.png', author: 'GameSyte', tags: generateTags('2D Rocket League'), aiHint: generateAiHint('2D Rocket League') },
    { id: 'pizzatower', title: 'Pizza Tower', src: 'https://gamesyte.github.io/pizzatower/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/pizzatower/images/menubg.png', author: 'GameSyte', tags: generateTags('Pizza Tower'), aiHint: generateAiHint('Pizza Tower') },
    { id: 'monstertracks', title: 'Monster Tracks', src: 'https://gamesyte.github.io/monstertracks/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/monstertracks/webapp/cover.jpg', author: 'GameSyte', tags: generateTags('Monster Tracks'), aiHint: generateAiHint('Monster Tracks') },
    { id: 'tabs', title: 'Totally Accurate Battle Simulator', src: 'https://gamesyte.github.io/tabs/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/tabs/unnamed.png', author: 'GameSyte', tags: generateTags('Totally Accurate Battle Simulator'), aiHint: generateAiHint('Totally Accurate Battle Simulator') },
    { id: 'csgoclicker', title: 'CSGO Case Clicker', src: 'https://gamesyte.github.io/csgoclicker/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/csgoclicker/images/case1.png', author: 'GameSyte', tags: generateTags('CSGO Case Clicker'), aiHint: generateAiHint('CSGO Case Clicker') },
    { id: 'thefinalearth2', title: 'The Final Earth 2', src: 'https://gamesyte.github.io/thefinalearth2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/thefinalearth2/icons/favicon.png', author: 'GameSyte', tags: generateTags('The Final Earth 2'), aiHint: generateAiHint('The Final Earth 2') },
    { id: 'baldis-basics', title: 'Baldi\'s Basics', src: 'https://gamesyte.github.io/baldis-basics/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/baldis-basics/splash.png', author: 'GameSyte', tags: generateTags('Baldi\'s Basics'), aiHint: generateAiHint('Baldi\'s Basics') },
    { id: 'cubefield', title: 'Cubefield', src: 'https://gamesyte.github.io/cubefield/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/cubefield/assets/unnamed.png', author: 'GameSyte', tags: generateTags('Cubefield'), aiHint: generateAiHint('Cubefield') },
    { id: 'mcclassic', title: 'Minecraft Classic', src: 'https://gamesyte.github.io/mcclassic/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/mcclassic/assets/textures/previews/2.png', author: 'GameSyte', tags: generateTags('Minecraft Classic'), aiHint: generateAiHint('Minecraft Classic') },
    { id: 'bit-planes', title: 'Bit Planes', src: 'https://gamesyte.github.io/bit-planes/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/bit-planes/bitplanes.png', author: 'GameSyte', tags: generateTags('Bit Planes'), aiHint: generateAiHint('Bit Planes') },
    { id: 'snowrider3d', title: 'Snow Rider 3D', src: 'https://gamesyte.github.io/snowrider3d/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/snowrider3d/snow.png', author: 'GameSyte', tags: generateTags('Snow Rider 3D'), aiHint: generateAiHint('Snow Rider 3D') },
    { id: 'dadish', title: 'Dadish', src: 'https://gamesyte.github.io/dadish/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/dadish/favicon.png', author: 'GameSyte', tags: generateTags('Dadish'), aiHint: generateAiHint('Dadish') },
    { id: 'dadish2', title: 'Dadish 2', src: 'https://gamesyte.github.io/dadish2/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/dadish2/favicon.png', author: 'GameSyte', tags: generateTags('Dadish 2'), aiHint: generateAiHint('Dadish 2') },
    { id: 'dadish3', title: 'Dadish 3', src: 'https://gamesyte.github.io/dadish3/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/dadish3/splash.png', author: 'GameSyte', tags: generateTags('Dadish 3'), aiHint: generateAiHint('Dadish 3') },
    { id: 'watermelongame', title: 'Watermelon Game', src: 'https://gamesyte.github.io/watermelongame/index.html', width: 800, height: 600, thumbnail: 'https://gamesyte.github.io/watermelongame/assets/sprites/tittle.png', author: 'GameSyte', tags: generateTags('Watermelon Game'), aiHint: generateAiHint('Watermelon Game') },
];
